services:
    postgres:
      container_name: nestjs-postgres
      image: postgres:14
      restart: always
      ports:
        - '5555:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./nestjs-postgres:/var/lib/postgresql/data